package sall.good.confluent.etl.practice.model.oracle.item

import java.time.Instant

// com.rakuten.travel.kadas.logic.autogenerated.model.ItDpItems
data class DpItems(
        val id: String,
        val itemCode: String,
        val providerId: String,
        val zipCode: String,
        val countryCode: String,
        val airportCode: String,
        val longitude: Double,
        val latitude: Double,
        val stopped: Boolean,
        val requested: Boolean,
        val outrightBought: Boolean,
        override val createdAt: Instant,
        override val updatedAt: Instant,
        override val active: Boolean
) : CommonProperties
