package sall.good.confluent.etl.practice.model.oracle.item

import java.time.Instant

// com.rakuten.travel.kadas.logic.autogenerated.model.ItDpItems
data class DwrItems(
        val id: String,
        val name: String,
        val description: String,
        val language: String,
        val address1: String,
        val address2: String,
        override val createdAt: Instant,
        override val updatedAt: Instant,
        override val active: Boolean
) : CommonProperties
