version: '3.6'
services:
  # MongoDB Replica Set
  mongo1:
    image: "mongo:4.2-bionic"
    container_name: mongo1
    command: --replSet rs0 --oplogSize 128
    volumes:
      - rs1:/data/db
      - ./sample:/sample
    networks:
      - localnet
    ports:
      - "27017:27017"
    restart: always
  mongo2:
    image: "mongo:4.2-bionic"
    container_name: mongo2
    command: --replSet rs0 --oplogSize 128
    volumes:
      - rs2:/data/db
    networks:
      - localnet
    ports:
      - "27018:27017"
    restart: always
  mongo3:
    image: "mongo:4.2-bionic"
    container_name: mongo3
    command: --replSet rs0 --oplogSize 128
    volumes:
      - rs3:/data/db
    networks:
      - localnet
    ports:
      - "27019:27017"
    restart: always

networks:
  localnet:
    attachable: true

volumes:
  rs1:
  rs2:
  rs3:
